import mysql.connector as con
db = con.connect(user="root",password= "abhishek2006@",host= "localhost")
cur = db.cursor()
cur.execute("create database  library_management_system ;")
cur.execute("use library_management_system;")
cur.execute("create table book_details(id int not null ,book_name varchar(100),writer varchar(50),Availability varchar(20) );")
cur.execute("ALTER TABLE book_details ALTER Availability SET DEFAULT 'available'")
cur.execute("insert into book_details values(1,'To Kill a Mockingbird' ,'by Harper Lee',default)")
cur.execute("insert into book_details values(2,'Pride and Prejudice' ,'by Jane Austen',default)")
cur.execute("insert into book_details values(3,'The Diary of Anne Frank' ,'by Anne Frank',default)")
cur.execute("insert into book_details values(4,'1984' ,'by George Orwell',default)")
cur.execute("insert into book_details values(5,'Harry Potter and the Sorcerer s Stone' ,'by J.K. Rowling',default)")
db.commit()
cur.execute("create table reader(id int,name varchar(20),password varchar(20),book_issued  char(8) )")
cur.execute("create table staff(id int,name varchar(20),password varchar(20))")
cur.execute("create table admin(username varchar(20),password varchar(20))")
db.commit()
print("SET AN DEFAULT ADMIN ID AND PASS ")
a = input("Enter Username :")
b = input("Enter Password :")
cur.execute(f"insert into reader(name,password)values('{a}','{b}')")
cur.execute(f"insert into staff(name,password)values('{a}','{b}')")
cur.execute("insert into admin values ('{}','{}')".format(a,b))
db.commit()
cur.execute("create table req_book(id int ,bookname varchar(50),writer varchar(50))")